cola=[]
print("Entrada")
cola.append("Juan")
print("Llego:",cola[-1])
cola.append("Alejandra")
print("Llego:",cola[-1])
cola.append("Maria")
print("Llego:",cola[-1])
cola.append("Mario")
print("Llego:",cola[-1])
cola.append("Pepe")
print("Llego:",cola[-1])

print("Salida")
n=cola.pop(0)
print("se fue:",n)
n=cola.pop(0)
print("se fue:",n)
n=cola.pop(0)
print("se fue:",n)
n=cola.pop(0)
print("se fue:",n)
n=cola.pop(0)
print("se fue:",n)